dpc-sdp/tide

.env, composer.json, dev-init.sh, tide.info.yml
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-1213
Related PRs:
* Tide Core: https://github.com/dpc-sdp/tide_core/pull/57
* Tide Media: https://github.com/dpc-sdp/tide_media/pull/19
* Tide API: https://github.com/dpc-sdp/tide_api/pull/28
* Tide Site: https://github.com/dpc-sdp/tide_site/pull/18
* Tide Webform: https://github.com/dpc-sdp/tide_webform/pull/21
* Tide News: https://github.com/dpc-sdp/tide_news/pull/14
* Tide Page: https://github.com/dpc-sdp/tide_page/pull/14
* Tide Event: https://github.com/dpc-sdp/tide_event/pull/24
* Tide Landing Page: https://github.com/dpc-sdp/tide_landing_page/pull/63
* Tide Monsido: https://github.com/dpc-sdp/tide_monsido/pull/13
* Tide Search: https://github.com/dpc-sdp/tide_search/pull/11
* Tide: https://github.com/dpc-sdp/tide/pull/39
* …
=> [SDPA-1213] Upgraded JSON:API 2.0, JSON:API Extras 3.3, Webform 5.2, and Metatag.

composer.json
Update to use latest version of `tide_api`
=> Release 1.1.9

composer.json
https://digital-engagement.atlassian.net/browse/SDPA-2932
=> [SPDA-2932]update tide_webform version

composer.json
https://digital-engagement.atlassian.net/browse/SDPA-2274
=> [SDPA-2274] update content view

composer.json
https://digital-engagement.atlassian.net/browse/SDPA-2992
=> [SDPA-2992] fixed cache id issue

composer.json
https://digital-engagement.atlassian.net/projects/SDPA/issues/SDPA-1225
=> [SDPA-1225] Card event needs to be ristricted to 200 characters

composer.json
https://digital-engagement.atlassian.net/browse/SDPA-2990
=> [SDPA-2990]Update tide_webform version

composer.json
https://digital-engagement.atlassian.net/browse/SDPA-2992
=> [SDPA-2992]updated tide_api module to 1.2.11

composer.json
https://digital-engagement.atlassian.net/browse/SDPA-2992
=> [SDPA-2992]updated tide_site version

composer.json
https://digital-engagement.atlassian.net/browse/SDPA-2742
=> [SDPA-2742]Updated tide for scheduled transitions

composer.json
this PR relates https://digital-engagement.atlassian.net/projects/SDPA/issues/SDPA-2742
=> [SDPA-2742] Updated tide_search, tide_core and tide_test,

composer.json
On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>
=> Updated Tide Event 1.2.8.

composer.json
https://digital-engagement.atlassian.net/projects/SDPA/issues/SDPA-3143
1. fixes duplicated menu issue.
2. fixes config entity deleting issue.
=> [SDPA-3143]Updated tide_core

composer.json
* tide_core 1.2.12
* tide_webform 1.2.11
* tide_site 1.2.12
* tide_api 1.2.12
=> Release 1.1.20.

composer.json
removing summary_contents view page
more details please see https://github.com/dpc-sdp/tide_site/pull/38
https://digital-engagement.atlassian.net/browse/SDPA-3224
=> [SDPA-3224] Updated tide_site to 1.1.14

composer.json
1. [SDPA-3231] Fixed timelines missed issue https://github.com/dpc-sdp/tide_core/pull/96
2. [SDPA-3015] adds link_field_autocomplete_filter https://github.com/dpc-sdp/tide_landing_page/pull/86
[SDPA-3231]: https://digital-engagement.atlassian.net/browse/SDPA-3231
[SDPA-3015]: https://digital-engagement.atlassian.net/browse/SDPA-3015
=> Release 1.1.23

composer.json
Jira Ticket - https://digital-engagement.atlassian.net/browse/SDPA-3735
1. Added tide_landing_page upgrade version.
2. tide_landing_page upgraded with youtube option in the social list paragraph field.
=> [SDPA-3735] Added tide_landing_page module version upgrade.

composer.json
1.5.15
tide_event
Addition of tide event module to correct location of config file.
=> Release 1.5.15

composer.json
1. Added new field instance for the header radio button (Which will be used to show H2 or H2 and H3 for table of contents)
=> Release 1.5.18

composer.json
On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>
=> Upgraded to Tide Core 1.6.15, Tide API 1.5.2, Tide Site 1.4.6.

composer.json
=> [SDPSUP-3951] Update tide_core

composer.json
Jira
https://digital-engagement.atlassian.net/browse/SW-1640
- https://github.com/dpc-sdp/tide_core/pull/322
=> Bumps tide_core

composer.json, patches/video_embed_field/video_embed_field_6.patch
Using a noncanonical repository (fork) that originates from a Drupal ticket for issue resolution can potentially lead to a broken composer. This may happen if the changes are merged into the main branch and the forked repository is subsequently closed and deleted.
=> Remove noncanonical repos

composer.json
**Changes**
1. Update `tide_core` to `3.2.15`
=> Update `tide_core` to `3.2.15`
